
version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server/
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server/build:/app/build
      - ./server/src:/app/src
      - ./server:/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client/
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ./client:/app
  socket:
      build:
        dockerfile: Dockerfile
        context: ./socket/
      ports:
        - "3000:3000"
      volumes:
        - /app/node_modules
        - ./socket:/app  
         